"""updated_at column

Revision ID: ab40d9e7899f
Revises: c58fd17c58b5
Create Date: 2023-08-07 20:22:12.007454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab40d9e7899f'
down_revision = 'c58fd17c58b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_plate', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_plate', 'updated_at')
    # ### end Alembic commands ###
