"""adding license_plate status_now column

Revision ID: c58fd17c58b5
Revises: 749f70e41678
Create Date: 2023-04-02 01:10:49.502934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c58fd17c58b5'
down_revision = '749f70e41678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_plate', sa.Column('active_now', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_plate', 'active_now')
    # ### end Alembic commands ###
